# Form implementation generated from reading ui file 'ui_imagedialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageDialog(object):
    def setupUi(self, ImageDialog):
        ImageDialog.setObjectName("ImageDialog")
        ImageDialog.resize(724, 611)
        font = QtGui.QFont()
        font.setFamily("TSCu_Times")
        font.setPointSize(12)
        ImageDialog.setFont(font)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=ImageDialog)
        self.calendarWidget.setGeometry(QtCore.QRect(130, 80, 392, 232))
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton = QtWidgets.QPushButton(parent=ImageDialog)
        self.pushButton.setGeometry(QtCore.QRect(520, 450, 153, 36))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=ImageDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 450, 100, 36))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=ImageDialog)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 440, 312, 36))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(ImageDialog)
        QtCore.QMetaObject.connectSlotsByName(ImageDialog)

    def retranslateUi(self, ImageDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageDialog.setWindowTitle(_translate("ImageDialog", "Dialog"))
        self.pushButton.setText(_translate("ImageDialog", "PushButton"))
        self.pushButton_2.setText(_translate("ImageDialog", "PushButton"))
        self.pushButton_3.setText(_translate("ImageDialog", "PushButton"))
